# Generated by Django 4.2.3 on 2023-08-02 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_pay',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 10, 32, 45, 351871), verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Пользователь'),
        ),
    ]
