# Generated by Django 4.2.3 on 2023-08-02 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_course_owner_lesson_owner_alter_payments_date_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_pay',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 14, 17, 44, 783373), verbose_name='Дата платежа'),
        ),
    ]
