# Generated by Django 4.2.3 on 2023-08-05 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_payments_date_pay_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date_pay',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 14, 22, 4, 399113), verbose_name='Дата платежа'),
        ),
    ]
