# Generated by Django 4.2.3 on 2023-08-16 10:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0008_alter_lesson_url_alter_payments_date_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_pay',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 17, 2, 39, 984842), verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
